/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import java.util.*;
import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AAListaAtribAAtrib extends PAAtrib
{
    private final LinkedList<PAAtrib> _atribuicoes_ = new LinkedList<PAAtrib>();

    public AAListaAtribAAtrib()
    {
        // Constructor
    }

    public AAListaAtribAAtrib(
        @SuppressWarnings("hiding") List<?> _atribuicoes_)
    {
        // Constructor
        setAtribuicoes(_atribuicoes_);

    }

    @Override
    public Object clone()
    {
        return new AAListaAtribAAtrib(
            cloneList(this._atribuicoes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAListaAtribAAtrib(this);
    }

    public LinkedList<PAAtrib> getAtribuicoes()
    {
        return this._atribuicoes_;
    }

    public void setAtribuicoes(List<?> list)
    {
        for(PAAtrib e : this._atribuicoes_)
        {
            e.parent(null);
        }
        this._atribuicoes_.clear();

        for(Object obj_e : list)
        {
            PAAtrib e = (PAAtrib) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._atribuicoes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atribuicoes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atribuicoes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAAtrib> i = this._atribuicoes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAAtrib) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
