/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import java.util.*;
import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AAListaExpAExp extends PAExp
{
    private final LinkedList<PAExp> _lista_ = new LinkedList<PAExp>();

    public AAListaExpAExp()
    {
        // Constructor
    }

    public AAListaExpAExp(
        @SuppressWarnings("hiding") List<?> _lista_)
    {
        // Constructor
        setLista(_lista_);

    }

    @Override
    public Object clone()
    {
        return new AAListaExpAExp(
            cloneList(this._lista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAListaExpAExp(this);
    }

    public LinkedList<PAExp> getLista()
    {
        return this._lista_;
    }

    public void setLista(List<?> list)
    {
        for(PAExp e : this._lista_)
        {
            e.parent(null);
        }
        this._lista_.clear();

        for(Object obj_e : list)
        {
            PAExp e = (PAExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._lista_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lista_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAExp> i = this._lista_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
