/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import java.util.*;
import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AArBlocoABloco extends PABloco
{
    private final LinkedList<PADecVariavel> _decVariavel_ = new LinkedList<PADecVariavel>();
    private final LinkedList<PAComando> _comando_ = new LinkedList<PAComando>();

    public AArBlocoABloco()
    {
        // Constructor
    }

    public AArBlocoABloco(
        @SuppressWarnings("hiding") List<?> _decVariavel_,
        @SuppressWarnings("hiding") List<?> _comando_)
    {
        // Constructor
        setDecVariavel(_decVariavel_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AArBlocoABloco(
            cloneList(this._decVariavel_),
            cloneList(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArBlocoABloco(this);
    }

    public LinkedList<PADecVariavel> getDecVariavel()
    {
        return this._decVariavel_;
    }

    public void setDecVariavel(List<?> list)
    {
        for(PADecVariavel e : this._decVariavel_)
        {
            e.parent(null);
        }
        this._decVariavel_.clear();

        for(Object obj_e : list)
        {
            PADecVariavel e = (PADecVariavel) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._decVariavel_.add(e);
        }
    }

    public LinkedList<PAComando> getComando()
    {
        return this._comando_;
    }

    public void setComando(List<?> list)
    {
        for(PAComando e : this._comando_)
        {
            e.parent(null);
        }
        this._comando_.clear();

        for(Object obj_e : list)
        {
            PAComando e = (PAComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comando_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVariavel_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVariavel_.remove(child))
        {
            return;
        }

        if(this._comando_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PADecVariavel> i = this._decVariavel_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PADecVariavel) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PAComando> i = this._comando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
