/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AArChamadaAComando extends PAComando
{
    private PAExp _chamada_;

    public AArChamadaAComando()
    {
        // Constructor
    }

    public AArChamadaAComando(
        @SuppressWarnings("hiding") PAExp _chamada_)
    {
        // Constructor
        setChamada(_chamada_);

    }

    @Override
    public Object clone()
    {
        return new AArChamadaAComando(
            cloneNode(this._chamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArChamadaAComando(this);
    }

    public PAExp getChamada()
    {
        return this._chamada_;
    }

    public void setChamada(PAExp node)
    {
        if(this._chamada_ != null)
        {
            this._chamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamada_ == child)
        {
            this._chamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamada_ == oldChild)
        {
            setChamada((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
