/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ABoolSimVariavel extends PVariavel
{
    private TSim _sim_;

    public ABoolSimVariavel()
    {
        // Constructor
    }

    public ABoolSimVariavel(
        @SuppressWarnings("hiding") TSim _sim_)
    {
        // Constructor
        setSim(_sim_);

    }

    @Override
    public Object clone()
    {
        return new ABoolSimVariavel(
            cloneNode(this._sim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolSimVariavel(this);
    }

    public TSim getSim()
    {
        return this._sim_;
    }

    public void setSim(TSim node)
    {
        if(this._sim_ != null)
        {
            this._sim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sim_ == child)
        {
            this._sim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sim_ == oldChild)
        {
            setSim((TSim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
