/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaBasicStatement extends PBasicStatement
{
    private PChamada _chamada_;
    private PSemicolon _semicolon_;

    public AChamadaBasicStatement()
    {
        // Constructor
    }

    public AChamadaBasicStatement(
        @SuppressWarnings("hiding") PChamada _chamada_,
        @SuppressWarnings("hiding") PSemicolon _semicolon_)
    {
        // Constructor
        setChamada(_chamada_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaBasicStatement(
            cloneNode(this._chamada_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaBasicStatement(this);
    }

    public PChamada getChamada()
    {
        return this._chamada_;
    }

    public void setChamada(PChamada node)
    {
        if(this._chamada_ != null)
        {
            this._chamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamada_ = node;
    }

    public PSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(PSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamada_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamada_ == child)
        {
            this._chamada_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamada_ == oldChild)
        {
            setChamada((PChamada) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((PSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
