/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncaoDecOrDef extends PDecOrDef
{
    private PDecFuncao _decFuncao_;

    public ADecFuncaoDecOrDef()
    {
        // Constructor
    }

    public ADecFuncaoDecOrDef(
        @SuppressWarnings("hiding") PDecFuncao _decFuncao_)
    {
        // Constructor
        setDecFuncao(_decFuncao_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncaoDecOrDef(
            cloneNode(this._decFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncaoDecOrDef(this);
    }

    public PDecFuncao getDecFuncao()
    {
        return this._decFuncao_;
    }

    public void setDecFuncao(PDecFuncao node)
    {
        if(this._decFuncao_ != null)
        {
            this._decFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decFuncao_ == child)
        {
            this._decFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decFuncao_ == oldChild)
        {
            setDecFuncao((PDecFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
