/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ADirectStatementComando extends PComando
{
    private PDirectStatement _directStatement_;

    public ADirectStatementComando()
    {
        // Constructor
    }

    public ADirectStatementComando(
        @SuppressWarnings("hiding") PDirectStatement _directStatement_)
    {
        // Constructor
        setDirectStatement(_directStatement_);

    }

    @Override
    public Object clone()
    {
        return new ADirectStatementComando(
            cloneNode(this._directStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADirectStatementComando(this);
    }

    public PDirectStatement getDirectStatement()
    {
        return this._directStatement_;
    }

    public void setDirectStatement(PDirectStatement node)
    {
        if(this._directStatement_ != null)
        {
            this._directStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._directStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._directStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._directStatement_ == child)
        {
            this._directStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._directStatement_ == oldChild)
        {
            setDirectStatement((PDirectStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
