/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AExpAux extends PExpAux
{
    private TSepParam _sepParam_;
    private PExp _exp_;

    public AExpAux()
    {
        // Constructor
    }

    public AExpAux(
        @SuppressWarnings("hiding") TSepParam _sepParam_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setSepParam(_sepParam_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AExpAux(
            cloneNode(this._sepParam_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAux(this);
    }

    public TSepParam getSepParam()
    {
        return this._sepParam_;
    }

    public void setSepParam(TSepParam node)
    {
        if(this._sepParam_ != null)
        {
            this._sepParam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepParam_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sepParam_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sepParam_ == child)
        {
            this._sepParam_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sepParam_ == oldChild)
        {
            setSepParam((TSepParam) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
