/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AMandeDeVoltaBasicStatement extends PBasicStatement
{
    private TMande _mande_;
    private TDe _de_;
    private TVolta _volta_;
    private PExp _exp_;
    private PSemicolon _semicolon_;

    public AMandeDeVoltaBasicStatement()
    {
        // Constructor
    }

    public AMandeDeVoltaBasicStatement(
        @SuppressWarnings("hiding") TMande _mande_,
        @SuppressWarnings("hiding") TDe _de_,
        @SuppressWarnings("hiding") TVolta _volta_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PSemicolon _semicolon_)
    {
        // Constructor
        setMande(_mande_);

        setDe(_de_);

        setVolta(_volta_);

        setExp(_exp_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AMandeDeVoltaBasicStatement(
            cloneNode(this._mande_),
            cloneNode(this._de_),
            cloneNode(this._volta_),
            cloneNode(this._exp_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMandeDeVoltaBasicStatement(this);
    }

    public TMande getMande()
    {
        return this._mande_;
    }

    public void setMande(TMande node)
    {
        if(this._mande_ != null)
        {
            this._mande_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mande_ = node;
    }

    public TDe getDe()
    {
        return this._de_;
    }

    public void setDe(TDe node)
    {
        if(this._de_ != null)
        {
            this._de_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._de_ = node;
    }

    public TVolta getVolta()
    {
        return this._volta_;
    }

    public void setVolta(TVolta node)
    {
        if(this._volta_ != null)
        {
            this._volta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._volta_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(PSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mande_)
            + toString(this._de_)
            + toString(this._volta_)
            + toString(this._exp_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mande_ == child)
        {
            this._mande_ = null;
            return;
        }

        if(this._de_ == child)
        {
            this._de_ = null;
            return;
        }

        if(this._volta_ == child)
        {
            this._volta_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mande_ == oldChild)
        {
            setMande((TMande) newChild);
            return;
        }

        if(this._de_ == oldChild)
        {
            setDe((TDe) newChild);
            return;
        }

        if(this._volta_ == oldChild)
        {
            setVolta((TVolta) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((PSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
