/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AMenorExp extends PExp
{
    private PExp _exp_;
    private TMenor _menor_;
    private POpcao _opcao_;

    public AMenorExp()
    {
        // Constructor
    }

    public AMenorExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") POpcao _opcao_)
    {
        // Constructor
        setExp(_exp_);

        setMenor(_menor_);

        setOpcao(_opcao_);

    }

    @Override
    public Object clone()
    {
        return new AMenorExp(
            cloneNode(this._exp_),
            cloneNode(this._menor_),
            cloneNode(this._opcao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public POpcao getOpcao()
    {
        return this._opcao_;
    }

    public void setOpcao(POpcao node)
    {
        if(this._opcao_ != null)
        {
            this._opcao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._menor_)
            + toString(this._opcao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._opcao_ == child)
        {
            this._opcao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._opcao_ == oldChild)
        {
            setOpcao((POpcao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
