/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ANadaTipoRetorno extends PTipoRetorno
{
    private TNada _nada_;

    public ANadaTipoRetorno()
    {
        // Constructor
    }

    public ANadaTipoRetorno(
        @SuppressWarnings("hiding") TNada _nada_)
    {
        // Constructor
        setNada(_nada_);

    }

    @Override
    public Object clone()
    {
        return new ANadaTipoRetorno(
            cloneNode(this._nada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANadaTipoRetorno(this);
    }

    public TNada getNada()
    {
        return this._nada_;
    }

    public void setNada(TNada node)
    {
        if(this._nada_ != null)
        {
            this._nada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nada_ == child)
        {
            this._nada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nada_ == oldChild)
        {
            setNada((TNada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
