/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ANegacaoExp extends PExp
{
    private TNot _not_;
    private POpcao _opcao_;

    public ANegacaoExp()
    {
        // Constructor
    }

    public ANegacaoExp(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") POpcao _opcao_)
    {
        // Constructor
        setNot(_not_);

        setOpcao(_opcao_);

    }

    @Override
    public Object clone()
    {
        return new ANegacaoExp(
            cloneNode(this._not_),
            cloneNode(this._opcao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegacaoExp(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public POpcao getOpcao()
    {
        return this._opcao_;
    }

    public void setOpcao(POpcao node)
    {
        if(this._opcao_ != null)
        {
            this._opcao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._opcao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._opcao_ == child)
        {
            this._opcao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._opcao_ == oldChild)
        {
            setOpcao((POpcao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
