/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ANumInteiroVariavel extends PVariavel
{
    private TNumInteiro _numInteiro_;

    public ANumInteiroVariavel()
    {
        // Constructor
    }

    public ANumInteiroVariavel(
        @SuppressWarnings("hiding") TNumInteiro _numInteiro_)
    {
        // Constructor
        setNumInteiro(_numInteiro_);

    }

    @Override
    public Object clone()
    {
        return new ANumInteiroVariavel(
            cloneNode(this._numInteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumInteiroVariavel(this);
    }

    public TNumInteiro getNumInteiro()
    {
        return this._numInteiro_;
    }

    public void setNumInteiro(TNumInteiro node)
    {
        if(this._numInteiro_ != null)
        {
            this._numInteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numInteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numInteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numInteiro_ == child)
        {
            this._numInteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numInteiro_ == oldChild)
        {
            setNumInteiro((TNumInteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
