/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ANumRealVariavel extends PVariavel
{
    private TNumReal _numReal_;

    public ANumRealVariavel()
    {
        // Constructor
    }

    public ANumRealVariavel(
        @SuppressWarnings("hiding") TNumReal _numReal_)
    {
        // Constructor
        setNumReal(_numReal_);

    }

    @Override
    public Object clone()
    {
        return new ANumRealVariavel(
            cloneNode(this._numReal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumRealVariavel(this);
    }

    public TNumReal getNumReal()
    {
        return this._numReal_;
    }

    public void setNumReal(TNumReal node)
    {
        if(this._numReal_ != null)
        {
            this._numReal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numReal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numReal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numReal_ == child)
        {
            this._numReal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numReal_ == oldChild)
        {
            setNumReal((TNumReal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
