/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import java.util.*;
import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AParam extends PParam
{
    private PParametro _parametro_;
    private final LinkedList<PParamAux> _paramAux_ = new LinkedList<PParamAux>();

    public AParam()
    {
        // Constructor
    }

    public AParam(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") List<?> _paramAux_)
    {
        // Constructor
        setParametro(_parametro_);

        setParamAux(_paramAux_);

    }

    @Override
    public Object clone()
    {
        return new AParam(
            cloneNode(this._parametro_),
            cloneList(this._paramAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParam(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public LinkedList<PParamAux> getParamAux()
    {
        return this._paramAux_;
    }

    public void setParamAux(List<?> list)
    {
        for(PParamAux e : this._paramAux_)
        {
            e.parent(null);
        }
        this._paramAux_.clear();

        for(Object obj_e : list)
        {
            PParamAux e = (PParamAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._paramAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._paramAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._paramAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        for(ListIterator<PParamAux> i = this._paramAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParamAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
