/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AParamAux extends PParamAux
{
    private TSepParam _sepParam_;
    private PParametro _parametro_;

    public AParamAux()
    {
        // Constructor
    }

    public AParamAux(
        @SuppressWarnings("hiding") TSepParam _sepParam_,
        @SuppressWarnings("hiding") PParametro _parametro_)
    {
        // Constructor
        setSepParam(_sepParam_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AParamAux(
            cloneNode(this._sepParam_),
            cloneNode(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamAux(this);
    }

    public TSepParam getSepParam()
    {
        return this._sepParam_;
    }

    public void setSepParam(TSepParam node)
    {
        if(this._sepParam_ != null)
        {
            this._sepParam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sepParam_ = node;
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sepParam_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sepParam_ == child)
        {
            this._sepParam_ = null;
            return;
        }

        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sepParam_ == oldChild)
        {
            setSepParam((TSepParam) newChild);
            return;
        }

        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
