/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class ASemicolon extends PSemicolon
{
    private TPtVirgula _ptVirgula_;

    public ASemicolon()
    {
        // Constructor
    }

    public ASemicolon(
        @SuppressWarnings("hiding") TPtVirgula _ptVirgula_)
    {
        // Constructor
        setPtVirgula(_ptVirgula_);

    }

    @Override
    public Object clone()
    {
        return new ASemicolon(
            cloneNode(this._ptVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASemicolon(this);
    }

    public TPtVirgula getPtVirgula()
    {
        return this._ptVirgula_;
    }

    public void setPtVirgula(TPtVirgula node)
    {
        if(this._ptVirgula_ != null)
        {
            this._ptVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ptVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ptVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ptVirgula_ == child)
        {
            this._ptVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ptVirgula_ == oldChild)
        {
            setPtVirgula((TPtVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
