/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class AVarExpVar extends PVar
{
    private PVar _var_;
    private TColEsq _colEsq_;
    private PExp _exp_;
    private TColDir _colDir_;

    public AVarExpVar()
    {
        // Constructor
    }

    public AVarExpVar(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TColEsq _colEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TColDir _colDir_)
    {
        // Constructor
        setVar(_var_);

        setColEsq(_colEsq_);

        setExp(_exp_);

        setColDir(_colDir_);

    }

    @Override
    public Object clone()
    {
        return new AVarExpVar(
            cloneNode(this._var_),
            cloneNode(this._colEsq_),
            cloneNode(this._exp_),
            cloneNode(this._colDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarExpVar(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TColEsq getColEsq()
    {
        return this._colEsq_;
    }

    public void setColEsq(TColEsq node)
    {
        if(this._colEsq_ != null)
        {
            this._colEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TColDir getColDir()
    {
        return this._colDir_;
    }

    public void setColDir(TColDir node)
    {
        if(this._colDir_ != null)
        {
            this._colDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._colEsq_)
            + toString(this._exp_)
            + toString(this._colDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._colEsq_ == child)
        {
            this._colEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._colDir_ == child)
        {
            this._colDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._colEsq_ == oldChild)
        {
            setColEsq((TColEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._colDir_ == oldChild)
        {
            setColDir((TColDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
