/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class TArrume extends Token
{
    public TArrume()
    {
        super.setText("arrume");
    }

    public TArrume(int line, int pos)
    {
        super.setText("arrume");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArrume(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArrume(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArrume text.");
    }
}
