/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class TAssim extends Token
{
    public TAssim()
    {
        super.setText("assim");
    }

    public TAssim(int line, int pos)
    {
        super.setText("assim");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAssim(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAssim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAssim text.");
    }
}
