/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class TFor extends Token
{
    public TFor()
    {
        super.setText("arrodeie");
    }

    public TFor(int line, int pos)
    {
        super.setText("arrodeie");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFor text.");
    }
}
