/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordel.node;

import cordel.analysis.*;

@SuppressWarnings("nls")
public final class TSim extends Token
{
    public TSim()
    {
        super.setText("sim");
    }

    public TSim(int line, int pos)
    {
        super.setText("sim");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSim(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSim text.");
    }
}
